# Model configuration
model:
  architecture: "resnet18"
  num_classes: 4
  pretrained: true
  dropout: 0.1

# Training configuration
training:
  batch_size: 32
  learning_rate: 0.0003
  weight_decay: 0.0001
  max_epochs: 15
  patience: 3
  min_delta: 0.001
  
# Optimizer configuration
optimizer:
  name: "adam"
  betas: [0.9, 0.999]
  eps: 1e-8

# Scheduler configuration
scheduler:
  name: "steplr"
  step_size: 5
  gamma: 0.9

# Data configuration
data:
  train_csv: "data/processed/train_f.csv"
  val_csv: "data/processed/val_f.csv"
  test_csv: "data/processed/test_f.csv"
  image_size: 224
  num_workers: 4

# Data augmentation
augmentation:
  train:
    random_resized_crop: 224
    horizontal_flip_prob: 0.5
    rotation_degrees: 10
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
  
  val_test:
    resize: 224
    center_crop: 224

# Class labels
classes:
  - "on_fire"
  - "earthquake" 
  - "heavy_rainfall"
  - "fog"

# Paths
paths:
  model_dir: "models"
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Metrics to track
metrics:
  - "accuracy"
  - "precision"
  - "recall"
  - "f1_score"